In [3]:
import pandas as pd
from sqlalchemy import create_engine
import sqlite3

In [4]:
db_path = "/Users/huaiyao/Desktop/FA24-Group29/Project/ml/LastFM-Dataset-2020.db"

# Connect to the SQLite database
conn = sqlite3.connect(db_path)

query = "SELECT name FROM sqlite_master WHERE type='table';"
tables = pd.read_sql_query(query, conn)

print(tables)

# Close the connection
conn.close()

       name
0      tags
1  metadata

In [5]:
conn = sqlite3.connect(db_path)

# List tables in the database
query = "SELECT name FROM sqlite_master WHERE type='table';"
tables = pd.read_sql_query(query, conn)
print("Tables in the database:", tables)

table_name = 'metadata'
df = pd.read_sql_query(f"SELECT * FROM {table_name};", conn)
df_tags = pd.read_sql_query(f"SELECT * FROM {'tags'};", conn)

conn.close()

df.head()

Tables in the database:        name
0      tags
1  metadata

,id_dataset,id_spotify,url_spotify_preview,url_lastfm,artist,name
0,c2dbefcce2d7f84254e770b47e665dea,09ZQ5TmUG8TSL56n0knqrj,https://p.scdn.co/mp3-preview/4d26180e6961fd46...,https://www.last.fm/music/The+Killers/_/Mr.+Br...,The Killers,Mr. Brightside
1,48c73abec1cfd8cef3b92c5851bb69d4,06UfBBDISthj1ZJAtX4xjj,https://p.scdn.co/mp3-preview/d012e536916c927b...,https://www.last.fm/music/Oasis/_/Wonderwall,Oasis,Wonderwall
2,ae0c2975e946fc0931e82395296ff366,0keNu0t0tqsWtExGM3nT1D,https://p.scdn.co/mp3-preview/a1c11bb1cb231031...,https://www.last.fm/music/Nirvana/_/Come+as+Yo...,Nirvana,Come as You Are
3,1c2ba9fafad5df7aebc4e62c0adfd7dd,0ancVQ9wEcHVd0RrGICTE4,https://p.scdn.co/mp3-preview/399c401370438be4...,https://www.last.fm/music/Franz+Ferdinand/_/Ta...,Franz Ferdinand,Take Me Out
4,561e55c4c72ff7b862a56557ae1fe089,01QoK9DA7VTeTSE3MNzp4I,https://p.scdn.co/mp3-preview/e7eb60e9466bc3a2...,https://www.last.fm/music/Radiohead/_/Creep,Radiohead,Creep

In [6]:
df_tags.head()

,rock,electronic,alternative,indie,pop,female_vocalists,metal,alternative_rock,jazz,classic_rock,...,j_pop,pop_rock,polish,chill,blues_rock,avant_garde,drum_and_bass,new_age,ska,id_dataset
0,1,0,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,c2dbefcce2d7f84254e770b47e665dea
1,1,0,1,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,48c73abec1cfd8cef3b92c5851bb69d4
2,1,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,ae0c2975e946fc0931e82395296ff366
3,1,0,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1c2ba9fafad5df7aebc4e62c0adfd7dd
4,1,0,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,561e55c4c72ff7b862a56557ae1fe089

In [7]:
merged_df = pd.merge(df, df_tags, on='id_dataset', how='inner')

merged_df.to_csv('last_fm.csv', index=False)